<a href="https://colab.research.google.com/github/BrouthenKamel/Linear-Regression-Model/blob/main/Heart_Attack_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Drive already mounted at /content/drive; to attempt to forcibly remount, call drive.mount("/content/drive", force_remount=True).

In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [3]:
dataset = pd.read_csv("heart_statlog_cleveland_hungary_final.csv")

In [4]:
dataset.describe()

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
count,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000,1190.000000
mean,53.720168,0.763866,3.232773,132.153782,210.363866,0.213445,0.698319,139.732773,0.387395,0.922773,1.624370,0.528571
std,9.358203,0.424884,0.935480,18.368823,101.420489,0.409912,0.870359,25.517636,0.487360,1.086337,0.610459,0.499393
min,28.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,60.000000,0.000000,-2.600000,0.000000,0.000000
25%,47.000000,1.000000,3.000000,120.000000,188.000000,0.000000,0.000000,121.000000,0.000000,0.000000,1.000000,0.000000
50%,54.000000,1.000000,4.000000,130.000000,229.000000,0.000000,0.000000,140.500000,0.000000,0.600000,2.000000,1.000000
75%,60.000000,1.000000,4.000000,140.000000,269.750000,0.000000,2.000000,160.000000,1.000000,1.600000,2.000000,1.000000
max,77.000000,1.000000,4.000000,200.000000,603.000000,1.000000,2.000000,202.000000,1.000000,6.200000,3.000000,1.000000

In [5]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1190 entries, 0 to 1189
Data columns (total 12 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   age                  1190 non-null   int64
 1   sex                  1190 non-null   int64
 2   chest pain type      1190 non-null   int64
 3   resting bp s         1190 non-null   int64
 4   cholesterol          1190 non-null   int64
 5   fasting blood sugar  1190 non-null   int64
 6   resting ecg          1190 non-null   int64
 7   max heart rate       1190 non-null   int64
 8   exercise angina      1190 non-null   int64
 9   oldpeak              1190 non-null   float64
 10  ST slope             1190 non-null   int64
 11  target               1190 non-null   int64
dtypes: float64(1), int64(11)
memory usage: 111.7 KB

In [6]:
dataset.corr()

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope,target
age,1.000000,0.015096,0.149055,0.257692,-0.046472,0.178923,0.194595,-0.368676,0.188095,0.245093,0.237749,0.262029
sex,0.015096,1.000000,0.138405,-0.006443,-0.208441,0.110961,-0.022225,-0.181837,0.194380,0.096390,0.127913,0.311267
chest pain type,0.149055,0.138405,1.000000,0.009466,-0.109396,0.076492,0.035705,-0.337491,0.403428,0.224106,0.276949,0.460127
resting bp s,0.257692,-0.006443,0.009466,1.000000,0.099037,0.088235,0.095860,-0.101357,0.142435,0.176111,0.089384,0.121415
cholesterol,-0.046472,-0.208441,-0.109396,0.099037,1.000000,-0.239778,0.150879,0.238028,-0.033261,0.057451,-0.100053,-0.198366
fasting blood sugar,0.178923,0.110961,0.076492,0.088235,-0.239778,1.000000,0.032124,-0.118689,0.053053,0.031193,0.145902,0.216695
resting ecg,0.194595,-0.022225,0.035705,0.095860,0.150879,0.032124,1.000000,0.058812,0.037821,0.126023,0.093629,0.073059
max heart rate,-0.368676,-0.181837,-0.337491,-0.101357,0.238028,-0.118689,0.058812,1.000000,-0.377691,-0.183688,-0.350750,-0.413278
exercise angina,0.188095,0.194380,0.403428,0.142435,-0.033261,0.053053,0.037821,-0.377691,1.000000,0.370772,0.393408,0.481467
oldpeak,0.245093,0.096390,0.224106,0.176111,0.057451,0.031193,0.126023,-0.183688,0.370772,1.000000,0.524639,0.398385
ST slope,0.237749,0.127913,0.276949,0.089384,-0.100053,0.145902,0.093629,-0.350750,0.393408,0.524639,1.000000,0.505608
target,0.262029,0.311267,0.460127,0.121415,-0.198366,0.216695,0.073059,-0.413278,0.481467,0.398385,0.505608,1.000000

In [7]:
x = dataset.drop(columns="target")
x

,age,sex,chest pain type,resting bp s,cholesterol,fasting blood sugar,resting ecg,max heart rate,exercise angina,oldpeak,ST slope
0,40,1,2,140,289,0,0,172,0,0.0,1
1,49,0,3,160,180,0,0,156,0,1.0,2
2,37,1,2,130,283,0,1,98,0,0.0,1
3,48,0,4,138,214,0,0,108,1,1.5,2
4,54,1,3,150,195,0,0,122,0,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...
1185,45,1,1,110,264,0,0,132,0,1.2,2
1186,68,1,4,144,193,1,0,141,0,3.4,2
1187,57,1,4,130,131,0,0,115,1,1.2,2
1188,57,0,2,130,236,0,2,174,0,0.0,2
1189,38,1,3,138,175,0,0,173,0,0.0,1

In [8]:
y = dataset['target']
y

0       0
1       1
2       0
3       1
4       0
       ..
1185    1
1186    1
1187    1
1188    1
1189    0
Name: target, Length: 1190, dtype: int64

In [9]:
def sigmoid(x):
  return 1 / ( 1 + np.exp(-x) )

In [10]:
def model(datapoint, w, b):
  return sigmoid( np.dot(datapoint, w) + b )

In [11]:
def loss(datapoint, y , w , b):
  return ( -(y) * np.log(model(datapoint, w, b)) - (1-y) * np.log(1- model(datapoint,w,b)) )

In [12]:
def cost(x, y, w, b):
  total = x.shape[0]
  c = 0
  for i in range(total):
    c += loss(x[i,:], y[i], w, b)
  return c / total

In [13]:
def gradient_descent(x,y, w,b):
  m,n = x.shape
  dj_db = 0
  for i in range(m):
    dj_db += model(x[i,:], w, b) - y[i]
  dj_db = dj_db / m
  dj_dw = np.zeros(n)
  for j in range(n):
    for i in range(m):
      dj_dw[j] += ( model(x[i,:], w, b) - y[i] ) * x[i,j]
    dj_dw[j] = dj_dw[j] / m
  return dj_dw, dj_db

In [14]:
def update_params(x,y, w,b, alpha):
  m,n = x.shape
  dj_dw, dj_db = gradient_descent(x,y,w,b)
  new_w = np.zeros(n)
  new_b = 0
  for j in range(n):
    new_w[j] = w[j] - alpha * dj_dw[j]
  new_b = b - alpha * dj_db
  return new_w, new_b

In [15]:
x_train = x.to_numpy()
print(x_train.shape)
y_train = y.to_numpy()
print(y_train.shape)
w = np.zeros(11)
b = 0
alpha = 0.00008
iterations = 2000

(1190, 11)
(1190,)

In [16]:
def predict(x, threshold):
  if x>threshold:
    return 1
  else:
    return 0

In [17]:
m,n = x_train.shape
correct = 0
for i in range(iterations):
  if (i % 100 == 0):
    print("iteration : {} --> cost = {}".format(i, cost(x_train, y_train, w, b)))
    print("parameters : ")
    print("w = {}".format(w))
    print("b = {}".format(b))
    print("-------------------------")
  w,b = update_params(x_train, y_train, w,b, alpha)
for i in range(m):
  if ( predict( model( x_train[i,:] , w, b) , 0.5) == y_train[i] ) :
    correct += 1
print("accuracy = {}".format(( correct / m ) * 100) )

iteration : 0 --> cost = 0.6931471805599255
parameters :
w = [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
b = 0
-------------------------
iteration : 100 --> cost = 0.6044995401507143
parameters :
w = [ 0.01170331  0.00053067  0.0018519   0.01553133 -0.00301053  0.00028731
  0.00035835 -0.01403505  0.00086434  0.00167291  0.00124671]
b = 9.927352556976431e-05
-------------------------
iteration : 200 --> cost = 0.5912555948972225
parameters :
w = [ 0.017774    0.00099069  0.00340075  0.01984985 -0.00306357  0.00052195
  0.00066959 -0.02031177  0.00159489  0.0031203   0.00229003]
b = 0.00015762946223944426
-------------------------
iteration : 300 --> cost = 0.5871681184640175
parameters :
w = [ 0.0219006   0.00143022  0.00485261  0.02114385 -0.00310195  0.00074021
  0.00096035 -0.02306068  0.0022768   0.00448267  0.00326484]
b = 0.00020605375589187528
-------------------------
iteration : 400 --> cost = 0.5850735021949994
parameters :
w = [ 0.02500242  0.00185989  0.00625602  0.02123909 -0.00312236  0.00095048
  0.00123867 -0.02433776  0.0029363   0.00580352  0.00420606]
b = 0.00024921869757557657
-------------------------
iteration : 500 --> cost = 0.5835992209619001
parameters :
w = [ 0.02747189  0.00228407  0.00763112  0.02085038 -0.00313265  0.00115618
  0.00150828 -0.02494321  0.00358404  0.0071008   0.00512818]
b = 0.0002891609820486144
-------------------------
iteration : 600 --> cost = 0.5824050724285078
parameters :
w = [ 0.02950441  0.00270481  0.00898746  0.02028748 -0.00313788  0.00135897
  0.00177125 -0.0252303   0.00422493  0.00838294  0.00603803]
b = 0.0003268902138302176
-------------------------
iteration : 700 --> cost = 0.5813791602820405
parameters :
w = [ 0.03120942  0.00312316  0.01033004  0.01968865 -0.00314067  0.00155969
  0.00202882 -0.02536442  0.00486134  0.00965421  0.00693912]
b = 0.00036296189685973564
-------------------------
iteration : 800 --> cost = 0.580470076724356
parameters :
w = [ 0.03265484  0.00353966  0.01166166  0.01911408 -0.00314231  0.00175884
  0.00228188 -0.02542497  0.00549452  0.0109169   0.00783342]
b = 0.0003977127506851927
-------------------------
iteration : 900 --> cost = 0.5796469384438172
parameters :
w = [ 0.03388693  0.00395465  0.01298409  0.01858743 -0.00314343  0.00195674
  0.00253105 -0.02545036  0.00612513  0.01217239  0.00872209]
b = 0.00043136659853550244
-------------------------
iteration : 1000 --> cost = 0.5788884164036651
parameters :
w = [ 0.03493973  0.00436834  0.01429849  0.01811533 -0.0031443   0.00215359
  0.00277685 -0.02545914  0.00675357  0.01342152  0.00960592]
b = 0.0004640848734729012
-------------------------
iteration : 1100 --> cost = 0.5781789464040598
parameters :
w = [ 0.03583979  0.00478086  0.01560572  0.01769675 -0.00314505  0.00234954
  0.00301967 -0.02546015  0.00738007  0.01466487  0.01048545]
b = 0.0004959917802714746
-------------------------
iteration : 1200 --> cost = 0.5775069483028287
parameters :
w = [ 0.03660868  0.00519233  0.01690642  0.01732747 -0.00314572  0.00254473
  0.00325987 -0.02545752  0.0080048   0.01590289  0.01136109]
b = 0.0005271873783505457
-------------------------
iteration : 1300 --> cost = 0.576863746832243
parameters :
w = [ 0.0372644   0.00560282  0.01820114  0.01700224 -0.00314634  0.00273925
  0.00349772 -0.02545315  0.00862789  0.01713591  0.01223319]
b = 0.000557754744762339
-------------------------
iteration : 1400 --> cost = 0.5762428248971779
parameters :
w = [ 0.03782222  0.00601241  0.01949032  0.01671577 -0.0031469   0.00293317
  0.00373348 -0.02544786  0.00924941  0.01836421  0.01310202]
b = 0.0005877641611876168
-------------------------
iteration : 1500 --> cost = 0.5756392794092944
parameters :
w = [ 0.03829518  0.00642115  0.02077432  0.01646312 -0.00314741  0.00312657
  0.00396737 -0.02544198  0.00986946  0.01958803  0.01396781]
b = 0.0006172757585049739
-------------------------
iteration : 1600 --> cost = 0.5750494175195386
parameters :
w = [ 0.03869453  0.00682911  0.02205349  0.01623986 -0.00314787  0.00331951
  0.00419956 -0.02543562  0.0104881   0.02080756  0.01483076]
b = 0.00064634132770421
-------------------------
iteration : 1700 --> cost = 0.5744704551424181
parameters :
w = [ 0.03902999  0.00723631  0.02332808  0.01604209 -0.00314827  0.00351203
  0.00443021 -0.02542883  0.01110537  0.02202298  0.01569105]
b = 0.000675005653619921
-------------------------
iteration : 1800 --> cost = 0.5739002912817558
parameters :
w = [ 0.03930996  0.00764279  0.02459835  0.01586641 -0.00314863  0.00370418
  0.00465947 -0.02542163  0.01172134  0.02323444  0.01654881]
b = 0.0007033075550971287
-------------------------
iteration : 1900 --> cost = 0.5733373388548044
parameters :
w = [ 0.03954175  0.0080486   0.02586451  0.01570988 -0.00314894  0.003896
  0.00488745 -0.02541401  0.01233604  0.02444207  0.01740419]
b = 0.0007312807295593326
-------------------------
accuracy = 70.50420168067227