<a href="https://colab.research.google.com/github/BrouthenKamel/Linear-Regression-Model/blob/main/Linear_Regression_Predicting_Medical_Insurance.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Importing necessary modules

In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

Importing the dataset, exploring it.

In [2]:
dataset = pd.read_csv("insurance.csv")
dataset

      age     sex     bmi  children smoker     region      charges
0      19  female  27.900         0    yes  southwest  16884.92400
1      18    male  33.770         1     no  southeast   1725.55230
2      28    male  33.000         3     no  southeast   4449.46200
3      33    male  22.705         0     no  northwest  21984.47061
4      32    male  28.880         0     no  northwest   3866.85520
...   ...     ...     ...       ...    ...        ...          ...
1333   50    male  30.970         3     no  northwest  10600.54830
1334   18  female  31.920         0     no  northeast   2205.98080
1335   18  female  36.850         0     no  southeast   1629.83350
1336   21  female  25.800         0     no  southwest   2007.94500
1337   61  female  29.070         0    yes  northwest  29141.36030

[1338 rows x 7 columns]

Data summary description

In [3]:
dataset.describe()

               age          bmi     children       charges
count  1338.000000  1338.000000  1338.000000   1338.000000
mean     39.207025    30.663397     1.094918  13270.422265
std      14.049960     6.098187     1.205493  12110.011237
min      18.000000    15.960000     0.000000   1121.873900
25%      27.000000    26.296250     0.000000   4740.287150
50%      39.000000    30.400000     1.000000   9382.033000
75%      51.000000    34.693750     2.000000  16639.912515
max      64.000000    53.130000     5.000000  63770.428010

In [4]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1338 entries, 0 to 1337
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   age       1338 non-null   int64
 1   sex       1338 non-null   object
 2   bmi       1338 non-null   float64
 3   children  1338 non-null   int64
 4   smoker    1338 non-null   object
 5   region    1338 non-null   object
 6   charges   1338 non-null   float64
dtypes: float64(2), int64(2), object(3)
memory usage: 73.3+ KB

In [5]:
for i in dataset.columns:
  print(" column : {0} of type : {1} ".format(i , dataset[i].dtype) )

 column : age of type : int64
 column : sex of type : object
 column : bmi of type : float64
 column : children of type : int64
 column : smoker of type : object
 column : region of type : object
 column : charges of type : float64

In [6]:
dataset_backup = dataset

In [7]:
dataset = pd.get_dummies(dataset, columns = ['sex'])
dataset

,age,bmi,children,smoker,region,charges,sex_female,sex_male
0,19,27.900,0,yes,southwest,16884.92400,1,0
1,18,33.770,1,no,southeast,1725.55230,0,1
2,28,33.000,3,no,southeast,4449.46200,0,1
3,33,22.705,0,no,northwest,21984.47061,0,1
4,32,28.880,0,no,northwest,3866.85520,0,1
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,no,northwest,10600.54830,0,1
1334,18,31.920,0,no,northeast,2205.98080,1,0
1335,18,36.850,0,no,southeast,1629.83350,1,0
1336,21,25.800,0,no,southwest,2007.94500,1,0
1337,61,29.070,0,yes,northwest,29141.36030,1,0

In [8]:
dataset['smoker'] = dataset['smoker'].replace({'yes' : 1 , 'no' : 0})
dataset

,age,bmi,children,smoker,region,charges,sex_female,sex_male
0,19,27.900,0,1,southwest,16884.92400,1,0
1,18,33.770,1,0,southeast,1725.55230,0,1
2,28,33.000,3,0,southeast,4449.46200,0,1
3,33,22.705,0,0,northwest,21984.47061,0,1
4,32,28.880,0,0,northwest,3866.85520,0,1
...,...,...,...,...,...,...,...,...
1333,50,30.970,3,0,northwest,10600.54830,0,1
1334,18,31.920,0,0,northeast,2205.98080,1,0
1335,18,36.850,0,0,southeast,1629.83350,1,0
1336,21,25.800,0,0,southwest,2007.94500,1,0
1337,61,29.070,0,1,northwest,29141.36030,1,0

In [9]:
dataset.groupby(['region']).charges.mean()
dataset = dataset.drop(columns=['region'])

Normalizing data

In [10]:
dataset['age'] = dataset['age'] / dataset['age'].max()
dataset['bmi'] = dataset['bmi'] / dataset['bmi'].max()
dataset['children'] = dataset['children'] / dataset['children'].max()
dataset

           age       bmi  children  smoker      charges  sex_female  sex_male
0     0.296875  0.525127       0.0       1  16884.92400           1         0
1     0.281250  0.635611       0.2       0   1725.55230           0         1
2     0.437500  0.621118       0.6       0   4449.46200           0         1
3     0.515625  0.427348       0.0       0  21984.47061           0         1
4     0.500000  0.543572       0.0       0   3866.85520           0         1
...        ...       ...       ...     ...          ...         ...       ...
1333  0.781250  0.582910       0.6       0  10600.54830           0         1
1334  0.281250  0.600791       0.0       0   2205.98080           1         0
1335  0.281250  0.693582       0.0       0   1629.83350           1         0
1336  0.328125  0.485601       0.0       0   2007.94500           1         0
1337  0.953125  0.547149       0.0       1  29141.36030           1         0

[1338 rows x 7 columns]

In [11]:
y = dataset['charges']
y

0       16884.92400
1        1725.55230
2        4449.46200
3       21984.47061
4        3866.85520
           ...
1333    10600.54830
1334     2205.98080
1335     1629.83350
1336     2007.94500
1337    29141.36030
Name: charges, Length: 1338, dtype: float64

In [12]:
x = dataset.drop(columns='charges')
x

           age       bmi  children  smoker  sex_female  sex_male
0     0.296875  0.525127       0.0       1           1         0
1     0.281250  0.635611       0.2       0           0         1
2     0.437500  0.621118       0.6       0           0         1
3     0.515625  0.427348       0.0       0           0         1
4     0.500000  0.543572       0.0       0           0         1
...        ...       ...       ...     ...         ...       ...
1333  0.781250  0.582910       0.6       0           0         1
1334  0.281250  0.600791       0.0       0           1         0
1335  0.281250  0.693582       0.0       0           1         0
1336  0.328125  0.485601       0.0       0           1         0
1337  0.953125  0.547149       0.0       1           1         0

[1338 rows x 6 columns]

In [13]:
x = x.to_numpy()
x_train = x[:1000 , :]
x_test = x[1000: , :]

In [14]:
y = y.to_numpy()
y_train = y[:1000]
y_test = y[1000:]

**Initializing the parameters**

In [15]:
weights = np.random.rand(6)*20
bias = 3000
weights, bias

(array([ 7.36408595,  0.2028347 , 10.14393587,  5.23840851,  1.44966755,
        14.16231249]), 3000)

In [16]:
def predict(datapoint, w , b):
  return np.dot(datapoint,w) + b

In [17]:
def loss_function(datapoint, target, w, b):
  return ( ( predict(datapoint, w, b) - target ) ** 2 )

In [18]:
def cost_function(x_train, y_train, w, b, length):
  cost = 0
  for i in range(length):
    cost += loss_function(x_train[i,:], y_train[i], w, b)
  return cost/(2*length)

In [19]:
def update_params(x_train, y_train,length, w, b, learn_rate):
  save_w = w
  update_w = np.zeros(6)
  save_b = b
  update_b = 0
  for j in range(len(w)):
    difference_w = 0
    difference_b = 0
    for i in range(len(y_train)):
      difference_w += ( predict(x_train[i,:], save_w, save_b) - y_train[i] ) * x_train[i,j]
      difference_b += ( predict(x_train[i,:], save_w, save_b) - y_train[i] )
    update_w[j] = w[j] - learn_rate*difference_w/length
    #print("new w = {}".format(update_w))
  update_b = b - learn_rate*difference_b/length
  #print("new b = {}".format(update_b))
  return [update_w, update_b]

In [20]:
iterations = 50
alpha = 0.1
max = len(y_train)
for i in range(iterations):
  print("params -> w = {} , b = {}".format(weights,bias))
  print("iteration : {0} cost-function = {1}".format(i, cost_function(x_train, y_train, weights, bias, max)))
  print("/////////////////////////////////////////////////////////////////////////")
  new_params = update_params(x_train, y_train, max, weights, bias , alpha )
  weights = new_params[0]
  bias = new_params[1]

params -> w = [ 7.36408595  0.2028347  10.14393587  5.23840851  1.44966755 14.16231249] , b = 3000
iteration : 0 cost-function = 122330526.03311528
/////////////////////////////////////////////////////////////////////////
params -> w = [717.58974465 610.27428057 242.48614736 575.3820475  476.04814291
 545.56308017] , b = 4005.9992430402117
iteration : 1 cost-function = 97659885.26538222
/////////////////////////////////////////////////////////////////////////
params -> w = [1271.58819866 1076.15678916  420.0896462  1088.20378626  830.6574286
  950.43024682] , b = 4765.475695382973
iteration : 2 cost-function = 82631746.96840225
/////////////////////////////////////////////////////////////////////////
params -> w = [1705.65686263 1431.38884016  555.68856981 1555.83825226 1093.46545027
 1257.90964252] , b = 5335.763112743814
iteration : 3 cost-function = 73304296.53004168
/////////////////////////////////////////////////////////////////////////
params -> w = [2047.66716579 1701.72373966  659.06110691 1987.62271306 1286.10117097
 1490.3976077 ] , b = 5760.886798636384
iteration : 4 cost-function = 67352626.28862903
/////////////////////////////////////////////////////////////////////////
params -> w = [2319.02021507 1906.93652879  737.71555665 2390.74598121 1425.15772611
 1665.10669659] , b = 6074.652442666456
iteration : 5 cost-function = 63405306.69385973
/////////////////////////////////////////////////////////////////////////
params -> w = [2536.14855941 2062.21151989  797.4171579  2770.74672035 1523.36200599
 1795.26803207] , b = 6303.018058014526
iteration : 6 cost-function = 60653174.457480036
/////////////////////////////////////////////////////////////////////////
params -> w = [2711.66940241 2179.20779368  842.59264494 3131.89610519 1590.47274549
 1891.05464088] , b = 6465.915406336965
iteration : 7 cost-function = 58618641.701106176
/////////////////////////////////////////////////////////////////////////
params -> w = [2855.27016017 2266.8774009   876.64090854 3477.49167604 1633.97013467
 1960.29052601] , b = 6578.648680644544
iteration : 8 cost-function = 57019661.20170047
/////////////////////////////////////////////////////////////////////////
params -> w = [2974.38848518 2332.09366409  902.17155469 3810.08299865 1659.58533881
 2008.9952032 ] , b = 6652.968561966555
iteration : 9 cost-function = 55689508.51454844
/////////////////////////////////////////////////////////////////////////
params -> w = [3074.73445967 2380.13365413  921.18809553 4131.64495686 1671.70708584
 2041.80188774] , b = 6697.8969935408595
iteration : 10 cost-function = 54529478.25657546
/////////////////////////////////////////////////////////////////////////
params -> w = [3160.69158985 2415.04868658  935.22862293 4443.71083184 1673.69385475
 2062.27865475] , b = 6720.360529457193
iteration : 11 cost-function = 53480989.27036686
/////////////////////////////////////////////////////////////////////////
params -> w = [3235.6247307  2439.94882789  945.47383282 4747.47450108 1668.11357595
 2073.17509053] , b = 6725.676686448338
iteration : 12 cost-function = 52509134.87066005
/////////////////////////////////////////////////////////////////////////
params -> w = [3302.1165421  2457.22136913  952.8299778  5043.86892393 1656.92766932
 2076.61172661] , b = 6717.927415900116
iteration : 13 cost-function = 51592982.076251484
/////////////////////////////////////////////////////////////////////////
params -> w = [3362.14906399 2468.69859306  957.99256715 5333.62641738 1641.63234013
 2074.2255347 ] , b = 6700.245894791046
iteration : 14 cost-function = 50719850.628694266
/////////////////////////////////////////////////////////////////////////
params -> w = [3417.24314789 2475.78660319  961.49528252 5617.32494816 1623.36705453
 2067.28167922] , b = 6675.0367537144575
iteration : 15 cost-function = 49881938.852995165
/////////////////////////////////////////////////////////////////////////
params -> w = [3468.56552624 2479.56425211  963.74754078 5895.42368657 1602.99781336
 2056.75935752] , b = 6644.145190837366
iteration : 16 cost-function = 49074333.44202159
/////////////////////////////////////////////////////////////////////////
params -> w = [3517.01103069 2480.85910896  965.06333874 6168.29031412 1581.18107461
 2043.4177405 ] , b = 6608.986835067074
iteration : 17 cost-function = 48293835.34786664
/////////////////////////////////////////////////////////////////////////
params -> w = [3563.26572704 2480.30579495  965.68340338 6436.22199873 1558.41281715
 2027.84663119] , b = 6570.647468304628
iteration : 18 cost-function = 47538266.94717316
/////////////////////////////////////////////////////////////////////////
params -> w = [3607.85539605 2478.3907794   965.79220117 6699.46150707 1535.06619548
 2010.50538687] , b = 6529.959602317527
iteration : 19 cost-function = 46806063.033536166
/////////////////////////////////////////////////////////////////////////
params -> w = [3651.18276138 2475.48677857  965.53099969 6958.20958247 1511.42043443
 1991.75282775] , b = 6487.561282144112
iteration : 20 cost-function = 46096029.20418364
/////////////////////////////////////////////////////////////////////////
params -> w = [3693.55607622 2471.87917049  965.00789785 7212.63445506 1487.68299819
 1971.870223  ] , b = 6443.94124115411
iteration : 21 cost-function = 45407198.98071852
/////////////////////////////////////////////////////////////////////////
params -> w = [3735.21107442 2467.78627887  964.30552811 7462.87914956 1464.00659542
 1951.07896009] , b = 6399.473575473652
iteration : 22 cost-function = 44738749.17444724
/////////////////////////////////////////////////////////////////////////
params -> w = [3776.32782609 2463.37494894  963.48697122 7709.06710173 1440.5022201
 1929.55413022] , b = 6354.444370277225
iteration : 23 cost-function = 44089949.61870105
/////////////////////////////////////////////////////////////////////////
params -> w = [3817.04368043 2458.77250802  962.60029814 7951.30647592 1417.24914884
 1907.43497708] , b = 6309.072145879904
iteration : 24 cost-function = 43460133.18641602
/////////////////////////////////////////////////////////////////////////
params -> w = [3857.46320389 2454.07594992  961.68205788 8189.69348507 1394.30260211
 1884.83293595] , b = 6263.5235580270755
iteration : 25 cost-function = 42848677.787797555
/////////////////////////////////////////////////////////////////////////
params -> w = [3897.66581106 2449.35898739  960.75995586 8424.31494454 1371.69961225
 1861.83782165] , b = 6217.925453863765
iteration : 26 cost-function = 42254995.449346595
/////////////////////////////////////////////////////////////////////////
params -> w = [3937.71162382 2444.67746763  959.85491064 8655.25023748 1349.46351517
 1838.52259429] , b = 6172.374129418175
iteration : 27 cost-function = 41678525.58435395
/////////////////////////////////////////////////////////////////////////
params -> w = [3977.64597002 2440.07353056  958.98263338 8882.57282823 1327.60738605
 1814.9470321 ] , b = 6126.942438120651
iteration : 28 cost-function = 41118730.74964541
/////////////////////////////////////////////////////////////////////////
params -> w = [4017.50283742 2435.57880187  958.1548406  9106.35142855 1306.13666467
 1791.1605645 ] , b = 6081.685249129154
iteration : 29 cost-function = 40575093.88203111
/////////////////////////////////////////////////////////////////////////
params -> w = [4057.30752543 2431.2168447   957.38018565 9326.6508971  1285.05115911
 1767.2044594 ] , b = 6036.643638470242
iteration : 30 cost-function = 40047116.419993035
/////////////////////////////////////////////////////////////////////////
params -> w = [4097.07868083 2427.00504219  956.66497382 9543.53293401 1264.34657285
 1743.1135143 ] , b = 5991.8481071102515
iteration : 31 cost-function = 39534316.95921673
/////////////////////////////////////////////////////////////////////////
params -> w = [4136.8298605  2422.95604277  956.01371162 9757.05661807 1244.01566631
 1718.91736554] , b = 5947.321051808841
iteration : 32 cost-function = 39036230.23398425
/////////////////////////////////////////////////////////////////////////
params -> w = [4176.57073086 2419.07886998  955.4295285  9967.27882284 1224.04913827
 1694.64150396] , b = 5903.078662187865
iteration : 33 cost-function = 38552406.301066324
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4216.30798854  2415.37977437   954.9145007  10174.25453977
  1204.43629279  1670.30806444] , b = 5859.132377195534
iteration : 34 cost-function = 38082409.852720775
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4256.04606682  2411.8628876    954.46989993 10378.0371299
  1185.16554186  1645.93644142] , b = 5815.490003235289
iteration : 35 cost-function = 37625819.614914395
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4295.78767764  2408.53072446   954.09638433 10578.67852045
  1166.2247823   1621.54377023] , b = 5772.156572492449
iteration : 36 cost-function = 37182227.80434095
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4335.53422741  2405.3845683    953.79414509 10776.22935918
  1147.60167675  1597.14530505] , b = 5729.135001764395
iteration : 37 cost-function = 36751239.62813994
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4375.28613587  2402.42476674   953.56301903 10970.73913615
  1129.28386123  1572.75471691] , b = 5686.42659810319
iteration : 38 cost-function = 36332472.81635774
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4415.0430805   2399.65095862   953.402575   11162.25628039
  1111.25909684  1548.38433003] , b = 5644.031446831323
iteration : 39 cost-function = 35925557.18084557
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4454.80418386  2397.0622481    953.31218027 11350.82823726
  1093.51537895  1524.04531033] , b = 5601.948709237574
iteration : 40 cost-function = 35530134.19647508
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4494.56815702  2394.65733822   953.29105144 11536.50153089
  1076.04101402  1499.74781694] , b = 5560.176850922036
iteration : 41 cost-function = 35145856.60187323
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4534.33340932  2392.43463322   953.3382935  11719.32181503
  1058.82467206  1475.50112487] , b = 5518.713816892294
iteration : 42 cost-function = 34772388.01768375
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4574.09813235  2390.39231709   953.45292985 11899.33391511
  1041.85542057  1451.31372524] , b = 5477.5571657754235
iteration : 43 cost-function = 34409402.5808628
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4613.86036406  2388.52841359   953.6339253  12076.58186326
  1025.12274469  1427.19340799] , b = 5436.704172640481
iteration : 44 cost-function = 34056584.59383307
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4653.61803763  2386.84083232   953.88020368 12251.10892804
  1008.61655697  1403.14733079] , b = 5396.151907722341
iteration : 45 cost-function = 33713628.18752998
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4693.36901871  2385.32740383   954.19066136 12422.95763994
   992.32719952  1379.18207717] , b = 5355.89729664538
iteration : 46 cost-function = 33380236.997514725
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4733.1111337   2383.98590656   954.56417758 12592.16981365
   976.24544053  1355.30370596] , b = 5315.937166445979
iteration : 47 cost-function = 33056123.8524305
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4772.84219113  2382.81408727   954.99962241 12758.78656775
   960.36246677  1331.51779396] , b = 5276.26828069485
iteration : 48 cost-function = 32741010.474152192
/////////////////////////////////////////////////////////////////////////
params -> w = [ 4812.55999782  2381.80967668   955.49586273 12922.84834235
   944.66987322  1307.82947307] , b = 5236.8873662539445
iteration : 49 cost-function = 32434627.189041846
/////////////////////////////////////////////////////////////////////////

Testing the model

In [21]:
for i in range(len(y_test)):
  print(" predicted charge = {} , actual charge = {}".format(predict(x_test[i], weights, bias), y_test[i]))

 predicted charge = 23253.623181780902 , actual charge = 17361.7661
 predicted charge = 22851.447289510477 , actual charge = 34472.841
 predicted charge = 9457.835439169328 , actual charge = 1972.95
 predicted charge = 11447.727212911948 , actual charge = 21232.18226
 predicted charge = 11096.606720972497 , actual charge = 8627.5411
 predicted charge = 10485.086451757308 , actual charge = 4433.3877
 predicted charge = 10298.579152206468 , actual charge = 4438.2634
 predicted charge = 24967.86913130344 , actual charge = 24915.22085
 predicted charge = 9879.549295866887 , actual charge = 23241.47453
 predicted charge = 11783.033234558248 , actual charge = 9957.7216
 predicted charge = 10787.907870288243 , actual charge = 8269.044
 predicted charge = 24111.070796935877 , actual charge = 18767.7377
 predicted charge = 13010.257009486697 , actual charge = 36580.28216
 predicted charge = 11759.935497464241 , actual charge = 8765.249
 predicted charge = 10244.849308027638 , actual charge = 5383.536
 predicted charge = 12096.179646785138 , actual charge = 12124.9924
 predicted charge = 8861.326194502875 , actual charge = 2709.24395
 predicted charge = 10013.2435408734 , actual charge = 3987.926
 predicted charge = 12399.693370019006 , actual charge = 12495.29085
 predicted charge = 9566.043189291184 , actual charge = 26018.95052
 predicted charge = 12006.800971078625 , actual charge = 8798.593
 predicted charge = 22843.073736667935 , actual charge = 35595.5898
 predicted charge = 24937.910916674515 , actual charge = 42211.1382
 predicted charge = 9083.00735477281 , actual charge = 1711.0268
 predicted charge = 11912.513998242022 , actual charge = 8569.8618
 predicted charge = 9269.66545582639 , actual charge = 2020.177
 predicted charge = 22364.66494109089 , actual charge = 16450.8947
 predicted charge = 9064.511305400229 , actual charge = 21595.38229
 predicted charge = 11992.254907361506 , actual charge = 9850.432
 predicted charge = 10089.420574320338 , actual charge = 6877.9801
 predicted charge = 23950.195951215333 , actual charge = 21677.28345
 predicted charge = 24958.713184672008 , actual charge = 44423.803
 predicted charge = 9653.105147686958 , actual charge = 4137.5227
 predicted charge = 21897.543261239945 , actual charge = 13747.87235
 predicted charge = 12826.810353592497 , actual charge = 12950.0712
 predicted charge = 11825.401337406442 , actual charge = 12094.478
 predicted charge = 23278.07218947945 , actual charge = 37484.4493
 predicted charge = 24180.90744398778 , actual charge = 39725.51805
 predicted charge = 9444.229509716712 , actual charge = 2250.8352
 predicted charge = 9526.825729359723 , actual charge = 22493.65964
 predicted charge = 23120.84039514293 , actual charge = 20234.85475
 predicted charge = 8881.26569998173 , actual charge = 1704.70015
 predicted charge = 22457.880583425555 , actual charge = 33475.81715
 predicted charge = 9406.018025108202 , actual charge = 3161.454
 predicted charge = 12422.629067373018 , actual charge = 11394.06555
 predicted charge = 23960.78718671989 , actual charge = 21880.82
 predicted charge = 10511.00090332778 , actual charge = 7325.0482
 predicted charge = 23781.927729654024 , actual charge = 44501.3982
 predicted charge = 9222.56443024113 , actual charge = 3594.17085
 predicted charge = 24666.196990725643 , actual charge = 39727.614
 predicted charge = 11310.194683191137 , actual charge = 8023.13545
 predicted charge = 12517.835990674092 , actual charge = 14394.5579
 predicted charge = 11725.061397006808 , actual charge = 9288.0267
 predicted charge = 25038.899398310143 , actual charge = 25309.489
 predicted charge = 9136.156595189872 , actual charge = 3353.4703
 predicted charge = 11890.831944755835 , actual charge = 10594.50155
 predicted charge = 11061.273566654738 , actual charge = 8277.523
 predicted charge = 10963.33636842433 , actual charge = 17929.30337
 predicted charge = 9716.255952045542 , actual charge = 2480.9791
 predicted charge = 10614.987258565698 , actual charge = 4462.7218
 predicted charge = 9736.130680880138 , actual charge = 1981.5819
 predicted charge = 12246.895641555398 , actual charge = 11554.2236
 predicted charge = 26074.469197073384 , actual charge = 48970.2476
 predicted charge = 11066.520959644964 , actual charge = 6548.19505
 predicted charge = 10237.713228432698 , actual charge = 5708.867
 predicted charge = 10636.253747843388 , actual charge = 7045.499
 predicted charge = 12174.767953275434 , actual charge = 8978.1851
 predicted charge = 11350.425221264508 , actual charge = 5757.41345
 predicted charge = 12420.36301372388 , actual charge = 14349.8544
 predicted charge = 11841.825663062653 , actual charge = 10928.849
 predicted charge = 24224.11082930631 , actual charge = 39871.7043
 predicted charge = 12667.658125751208 , actual charge = 13974.45555
 predicted charge = 9474.846275558602 , actual charge = 1909.52745
 predicted charge = 11897.697589710626 , actual charge = 12096.6512
 predicted charge = 11497.612337918119 , actual charge = 13204.28565
 predicted charge = 10070.3400208046 , actual charge = 4562.8421
 predicted charge = 11315.590871094199 , actual charge = 8551.347
 predicted charge = 9240.692871703694 , actual charge = 2102.2647
 predicted charge = 23109.003358140926 , actual charge = 34672.1472
 predicted charge = 13340.5523034873 , actual charge = 15161.5344
 predicted charge = 9205.204073326096 , actual charge = 11884.04858
 predicted charge = 10346.77517778644 , actual charge = 4454.40265
 predicted charge = 10448.316001976522 , actual charge = 5855.9025
 predicted charge = 10511.01866584926 , actual charge = 4076.497
 predicted charge = 12576.605074548494 , actual charge = 15019.76005
 predicted charge = 23944.341937712226 , actual charge = 19023.26
 predicted charge = 11950.434629373447 , actual charge = 10796.35025
 predicted charge = 12217.015863086535 , actual charge = 11353.2276
 predicted charge = 12755.130805798379 , actual charge = 9748.9106
 predicted charge = 11718.154644900533 , actual charge = 10577.087
 predicted charge = 24751.63010864515 , actual charge = 41676.0811
 predicted charge = 11633.666828665402 , actual charge = 11286.5387
 predicted charge = 10264.866834977904 , actual charge = 3591.48
 predicted charge = 22241.65796642439 , actual charge = 33907.548
 predicted charge = 12192.855612449297 , actual charge = 11299.343
 predicted charge = 9661.411412780828 , actual charge = 4561.1885
 predicted charge = 25027.112121572238 , actual charge = 44641.1974
 predicted charge = 9663.370207295753 , actual charge = 1674.6323
 predicted charge = 11453.047710796276 , actual charge = 23045.56616
 predicted charge = 9736.805637750233 , actual charge = 3227.1211
 predicted charge = 22951.438448935776 , actual charge = 16776.30405
 predicted charge = 12355.627222181836 , actual charge = 11253.421
 predicted charge = 10616.985388679106 , actual charge = 3471.4096
 predicted charge = 12496.288243207648 , actual charge = 11363.2832
 predicted charge = 10622.70742761515 , actual charge = 20420.60465
 predicted charge = 11621.038037623086 , actual charge = 10338.9316
 predicted charge = 11183.02456600073 , actual charge = 8988.15875
 predicted charge = 11475.22582228859 , actual charge = 10493.9458
 predicted charge = 9988.897995692038 , actual charge = 2904.088
 predicted charge = 11379.378524984673 , actual charge = 8605.3615
 predicted charge = 11859.75128249652 , actual charge = 11512.405
 predicted charge = 24741.502679732144 , actual charge = 41949.2441
 predicted charge = 24582.616693699456 , actual charge = 24180.9335
 predicted charge = 10002.728320250353 , actual charge = 5312.16985
 predicted charge = 9324.2087169484 , actual charge = 2396.0959
 predicted charge = 12307.23289226749 , actual charge = 10807.4863
 predicted charge = 11874.855344896823 , actual charge = 9222.4026
 predicted charge = 23337.91744641289 , actual charge = 36124.5737
 predicted charge = 23861.689886987733 , actual charge = 38282.7495
 predicted charge = 9869.120100102326 , actual charge = 5693.4305
 predicted charge = 22362.288614555764 , actual charge = 34166.273
 predicted charge = 12062.571116936539 , actual charge = 8347.1643
 predicted charge = 25455.102366350202 , actual charge = 46661.4424
 predicted charge = 9816.96042935109 , actual charge = 18903.49141
 predicted charge = 23062.138419365467 , actual charge = 40904.1995
 predicted charge = 12027.332894261835 , actual charge = 14254.6082
 predicted charge = 11991.887624314268 , actual charge = 10214.636
 predicted charge = 10769.984257444281 , actual charge = 5836.5204
 predicted charge = 10720.910128102738 , actual charge = 14358.36437
 predicted charge = 8401.007479378242 , actual charge = 1728.897
 predicted charge = 11109.561273221927 , actual charge = 8582.3023
 predicted charge = 10968.468321108696 , actual charge = 3693.428
 predicted charge = 12608.690647716565 , actual charge = 20709.02034
 predicted charge = 10891.079541544495 , actual charge = 9991.03765
 predicted charge = 10120.510507005205 , actual charge = 19673.33573
 predicted charge = 11751.582867973146 , actual charge = 11085.5868
 predicted charge = 10774.442732361393 , actual charge = 7623.518
 predicted charge = 9094.398672567519 , actual charge = 3176.2877
 predicted charge = 10339.60735129144 , actual charge = 3704.3545
 predicted charge = 22107.869529326246 , actual charge = 36898.73308
 predicted charge = 12125.33170830653 , actual charge = 9048.0273
 predicted charge = 11270.00040971215 , actual charge = 7954.517
 predicted charge = 11183.491208559477 , actual charge = 27117.99378
 predicted charge = 11270.589016860986 , actual charge = 6338.0756
 predicted charge = 12102.77904993133 , actual charge = 9630.397
 predicted charge = 12466.909275476137 , actual charge = 11289.10925
 predicted charge = 25585.32627805025 , actual charge = 52590.82939
 predicted charge = 9073.747206072767 , actual charge = 2261.5688
 predicted charge = 11806.65996957671 , actual charge = 10791.96
 predicted charge = 11194.490834262751 , actual charge = 5979.731
 predicted charge = 8849.739318515118 , actual charge = 2203.73595
 predicted charge = 12159.130050393574 , actual charge = 12235.8392
 predicted charge = 24504.235961969087 , actual charge = 40941.2854
 predicted charge = 10576.757271884286 , actual charge = 5630.45785
 predicted charge = 11782.645353022335 , actual charge = 11015.1747
 predicted charge = 10421.938393540051 , actual charge = 7228.21565
 predicted charge = 23018.199403538263 , actual charge = 39722.7462
 predicted charge = 9291.942926830212 , actual charge = 14426.07385
 predicted charge = 9014.144521455155 , actual charge = 2459.7201
 predicted charge = 10394.939366640485 , actual charge = 3989.841
 predicted charge = 11127.94471825584 , actual charge = 7727.2532
 predicted charge = 11330.235554771403 , actual charge = 5124.1887
 predicted charge = 10687.872442881497 , actual charge = 18963.17192
 predicted charge = 8756.077956973155 , actual charge = 2200.83085
 predicted charge = 10695.327434536546 , actual charge = 7153.5539
 predicted charge = 9951.29878772514 , actual charge = 5227.98875
 predicted charge = 12612.723912089183 , actual charge = 10982.5013
 predicted charge = 9810.478473100662 , actual charge = 4529.477
 predicted charge = 10868.040998986227 , actual charge = 4670.64
 predicted charge = 10651.758447897904 , actual charge = 6112.35295
 predicted charge = 22348.451026161798 , actual charge = 17178.6824
 predicted charge = 24050.41528388923 , actual charge = 22478.6
 predicted charge = 12250.837135114936 , actual charge = 11093.6229
 predicted charge = 11056.745147673497 , actual charge = 6457.8434
 predicted charge = 10502.115790219483 , actual charge = 4433.9159
 predicted charge = 9009.376690988058 , actual charge = 2154.361
 predicted charge = 24426.382221573265 , actual charge = 23887.6627
 predicted charge = 10578.73005077779 , actual charge = 6496.886
 predicted charge = 9433.174377794734 , actual charge = 2899.48935
 predicted charge = 23252.6508859277 , actual charge = 19350.3689
 predicted charge = 11354.398876412746 , actual charge = 7650.77375
 predicted charge = 9287.60957733316 , actual charge = 2850.68375
 predicted charge = 9380.231445099114 , actual charge = 2632.992
 predicted charge = 11183.470285208026 , actual charge = 9447.3824
 predicted charge = 22423.090086548054 , actual charge = 18328.2381
 predicted charge = 11332.021267567787 , actual charge = 8603.8234
 predicted charge = 23252.89304355488 , actual charge = 37465.34375
 predicted charge = 12292.103063958635 , actual charge = 13844.7972
 predicted charge = 23795.12084103947 , actual charge = 21771.3423
 predicted charge = 9125.525934260964 , actual charge = 13126.67745
 predicted charge = 10328.466519373756 , actual charge = 5327.40025
 predicted charge = 10401.571346064025 , actual charge = 13725.47184
 predicted charge = 12167.275015298874 , actual charge = 13019.16105
 predicted charge = 11405.221389542092 , actual charge = 8671.19125
 predicted charge = 9452.194997223314 , actual charge = 4134.08245
 predicted charge = 9392.753612794273 , actual charge = 18838.70366
 predicted charge = 21997.178829322107 , actual charge = 33307.5508
 predicted charge = 11094.02650799448 , actual charge = 5699.8375
 predicted charge = 11021.425328008761 , actual charge = 6393.60345
 predicted charge = 10015.888530495675 , actual charge = 4934.705
 predicted charge = 10759.547148118516 , actual charge = 6198.7518
 predicted charge = 12161.38609406574 , actual charge = 8733.22925
 predicted charge = 9588.9788866452 , actual charge = 2055.3249
 predicted charge = 11987.385296104349 , actual charge = 9964.06
 predicted charge = 22372.20279677445 , actual charge = 18223.4512
 predicted charge = 10127.20484179445 , actual charge = 5116.5004
 predicted charge = 12542.079755065395 , actual charge = 36910.60803
 predicted charge = 24175.037024827547 , actual charge = 38415.474
 predicted charge = 23352.993247605882 , actual charge = 20296.86345
 predicted charge = 12809.025525684396 , actual charge = 12347.172
 predicted charge = 10786.276283670653 , actual charge = 5373.36425
 predicted charge = 11349.461742370007 , actual charge = 23563.01618
 predicted charge = 8808.891011517484 , actual charge = 1702.4553
 predicted charge = 11944.142485361468 , actual charge = 10806.839
 predicted charge = 9765.872413964564 , actual charge = 3956.07145
 predicted charge = 9600.755250008628 , actual charge = 12890.05765
 predicted charge = 10638.63491693561 , actual charge = 5415.6612
 predicted charge = 10734.25256188808 , actual charge = 4058.1161
 predicted charge = 24440.685712974562 , actual charge = 41661.602
 predicted charge = 10935.445034954675 , actual charge = 7537.1639
 predicted charge = 9576.103420281383 , actual charge = 4718.20355
 predicted charge = 11016.12607833866 , actual charge = 6593.5083
 predicted charge = 11406.660003091265 , actual charge = 8442.667
 predicted charge = 21822.036756794652 , actual charge = 26125.67477
 predicted charge = 10854.573854469469 , actual charge = 6858.4796
 predicted charge = 10604.60433737249 , actual charge = 4795.6568
 predicted charge = 10499.03431303726 , actual charge = 6640.54485
 predicted charge = 11714.938810650903 , actual charge = 7162.0122
 predicted charge = 12270.711863949531 , actual charge = 10594.2257
 predicted charge = 12237.48711263117 , actual charge = 11938.25595
 predicted charge = 25627.93621366284 , actual charge = 60021.39897
 predicted charge = 21704.623949502813 , actual charge = 20167.33603
 predicted charge = 11897.327885384839 , actual charge = 12479.70895
 predicted charge = 11923.564702295545 , actual charge = 11345.519
 predicted charge = 11168.293442776398 , actual charge = 8515.7587
 predicted charge = 9845.414604061029 , actual charge = 2699.56835
 predicted charge = 11874.068848102259 , actual charge = 14449.8544
 predicted charge = 11788.741938841267 , actual charge = 12224.35085
 predicted charge = 10878.382813027953 , actual charge = 6985.50695
 predicted charge = 10101.59199322946 , actual charge = 3238.4357
 predicted charge = 25764.54062568603 , actual charge = 47269.854
 predicted charge = 26457.439825096655 , actual charge = 49577.6624
 predicted charge = 9322.189988346316 , actual charge = 4296.2712
 predicted charge = 9733.60872026215 , actual charge = 3171.6149
 predicted charge = 9340.385627731688 , actual charge = 1135.9407
 predicted charge = 10649.932531347542 , actual charge = 5615.369
 predicted charge = 11264.049872664727 , actual charge = 9101.798
 predicted charge = 11066.356823489197 , actual charge = 6059.173
 predicted charge = 9276.144990798266 , actual charge = 1633.9618
 predicted charge = 23690.86750444153 , actual charge = 37607.5277
 predicted charge = 22722.83097007247 , actual charge = 18648.4217
 predicted charge = 8809.868149927786 , actual charge = 1241.565
 predicted charge = 22306.185028966443 , actual charge = 16232.847
 predicted charge = 11237.507803209714 , actual charge = 15828.82173
 predicted charge = 9946.960595670987 , actual charge = 4415.1588
 predicted charge = 11009.700406636564 , actual charge = 6474.013
 predicted charge = 12197.78757907216 , actual charge = 11436.73815
 predicted charge = 11651.141886334874 , actual charge = 11305.93455
 predicted charge = 12915.740474124521 , actual charge = 30063.58055
 predicted charge = 11108.20360693723 , actual charge = 10197.7722
 predicted charge = 9472.666246767949 , actual charge = 4544.2348
 predicted charge = 10458.710939736608 , actual charge = 3277.161
 predicted charge = 10683.67578190453 , actual charge = 6770.1925
 predicted charge = 10918.214970879579 , actual charge = 7337.748
 predicted charge = 11718.70931890767 , actual charge = 10370.91255
 predicted charge = 25483.47367703163 , actual charge = 26926.5144
 predicted charge = 11663.692241217133 , actual charge = 10704.47
 predicted charge = 22778.17632007454 , actual charge = 34254.05335
 predicted charge = 9135.590593119614 , actual charge = 1880.487
 predicted charge = 11699.798972365075 , actual charge = 8615.3
 predicted charge = 10164.344995901025 , actual charge = 3292.52985
 predicted charge = 9567.778238425963 , actual charge = 3021.80915
 predicted charge = 11841.854663821385 , actual charge = 14478.33015
 predicted charge = 10564.141815494997 , actual charge = 4747.0529
 predicted charge = 22750.329254586337 , actual charge = 17043.3414
 predicted charge = 11865.673722182712 , actual charge = 10959.33
 predicted charge = 9157.263051317474 , actual charge = 2741.948
 predicted charge = 9885.627704475693 , actual charge = 4357.04365
 predicted charge = 24055.54765126224 , actual charge = 22462.04375
 predicted charge = 9605.354841314282 , actual charge = 4189.1131
 predicted charge = 11259.799801884834 , actual charge = 8283.6807
 predicted charge = 24396.030957988558 , actual charge = 24535.69855
 predicted charge = 21546.716783607553 , actual charge = 14283.4594
 predicted charge = 9383.709620775953 , actual charge = 1720.3537
 predicted charge = 26009.202401016984 , actual charge = 47403.88
 predicted charge = 10780.20862459024 , actual charge = 8534.6718
 predicted charge = 9024.650471652647 , actual charge = 3732.6251
 predicted charge = 10208.242579713973 , actual charge = 5472.449
 predicted charge = 23230.85572358833 , actual charge = 38344.566
 predicted charge = 11547.193477418467 , actual charge = 7147.4728
 predicted charge = 10284.442543102265 , actual charge = 7133.9025
 predicted charge = 22570.955198663243 , actual charge = 34828.654
 predicted charge = 9114.31725469492 , actual charge = 1515.3449
 predicted charge = 11696.96691664568 , actual charge = 9301.89355
 predicted charge = 12007.591043391803 , actual charge = 11931.12525
 predicted charge = 9175.486009734448 , actual charge = 1964.78
 predicted charge = 9017.50040767913 , actual charge = 1708.92575
 predicted charge = 9820.256706350683 , actual charge = 4340.4409